Repository daeuniverse/dae-wing, pull requests merged in 2023-06, with the labels that each got.

#2 chore: add pre-commit hooks
  .editorconfig
  .pre-commit-config.yaml
  CODEOWNERS
  CONTRIBUTING.md
  Makefile
  README.md
Labels: chore

#34 fix(webrender): imported log but not used
  webrender/webrender.go
Labels: hotfix

#44 optimize: add User-Agent for subscription fetching
  Makefile
  cmd/cmd.go
  cmd/export.go
  cmd/run.go
  db/app.go
  graphql/service/general/dae_resolver.go
  graphql/service/subscription/mutation_utils.go
Labels: optimize

#46 fix: incorrectly ignored empty group
  Makefile
  db/app.go
  graphql/service/config/mutation_utils.go
Labels: fix

#48 fix: threw error if failed to subscribe any nodes
  graphql/service/subscription/mutation_utils.go
Labels: fix

#52 fix(running): colon in node name; dup node in filter; no node in group
  graphql/service/config/mutation_utils.go
Labels: fix, tested

#54 fix: should support must_xxx and must_rules
  dae/utils.go
  graphql/service/config/mutation_utils.go
Labels: enhancement, fix, tested
