Repository daeuniverse/dae-wing, pull requests merged in 2023-07, with the labels that each got.

#53 fix: removing node and updating/removing subscription should update reloading version
  graphql/service/node/mutation_utils.go
  graphql/service/subscription/mutation_utils.go
Labels: fix, tested

#56 feat: support cmd command to reset password
  cmd/cmd.go
  cmd/resetpass.go
  go.mod
  go.sum
  graphql/mutation.go
Labels: not-yet-tested, feature

#59 chore: fix build
  go.mod
  go.sum
Labels: chore, tested

#63 ci: add sync-upstream workflow
  .github/sync-upstream.yml
Labels: not-yet-tested, ci

#62 chore: add PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#65 ci(sync-upstream): update downstream workflow ref
  .github/workflows/sync-upstream.yml
Labels: tested, ci

#66 ci(sync-upstream): fix invalid downstream workflow ref
  .github/workflows/sync-upstream.yml
Labels: ci

#61 fix: potential stuck in reloading status
  dae/run.go
Labels: fix, not-yet-tested

#68 fix: building problem caused by new group filter format
  graphql/service/config/mutation_utils.go
Labels: fix, not-yet-tested

#73 chore/fix: unmatched annotations length
  graphql/service/config/mutation_utils.go
Labels: chore, fix, tested

#79 fix: unchangable `modified` status
  db/system.go
  graphql/service/config/mutation_utils.go
  graphql/service/general/dae_resolver.go
Labels: fix, not-yet-tested

#80 fix: should wait for network for wan ready
  dae/run.go
  dae/utils.go
  go.mod
  go.sum
Labels: fix, tested

#84 fix(Makefile): gzip unexpected filename
  Makefile
Labels: fix, not-yet-tested
