Repository daeuniverse/dae-wing, pull requests merged in 2023-08, with the labels that each got.

#97 chore/refactor: rework issue_templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/proposal.yml
  .github/ISSUE_TEMPLATE/support-request.yml
Labels: chore, refactor

#98 chore(pr_template): update section headers
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#96 chore: add -buildmode=pie
  Makefile
Labels: chore

#100 chore(Makefile): support BUILD_ARGS
  Makefile
Labels: chore

#101 chore/fix(Makefile): fix recursive LDFLAGS reference
  Makefile
Labels: chore, fix

#105 chore(codeowners): set @daeuniverse/governance as default owner
  CODEOWNERS
Labels: chore

#102 chore: amd64 and arm64 use PIE build mode by default
  Makefile
Labels: chore

#91 feat: support `updateNode`
  graphql/mutation.go
  graphql/root_schema.go
  graphql/service/node/mutation_utils.go
Labels: tested, feature

#111 hotfix(makefile): completely demise buildarg=pie
  Makefile
Labels: hotfix, not-yet-tested
